FROM node:19-alpine AS builder

WORKDIR /app

RUN npm install -g pnpm 

COPY package.json ./

COPY pnpm-lock.yaml ./

COPY . .

RUN pnpm install

RUN pnpm build



FROM node:19-alpine AS runner

WORKDIR /app

COPY --from=builder ./app/dist  ./dist

ENV NODE_ENV=production

EXPOSE 4000

CMD ["node","dist","index.js"]
