version: '3.8'

name: freshness-prod
services:
  api:  
    env_file:
      - .env
    # environment:
    #   - NODE_ENV=production
    #   - PORT=4000 
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: api_prod_c
    expose:
      - 4000
    ports:
      - 3002:4000
    depends_on:
      - db 
    networks:
    - irene_network_prod

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
       - ./data/postgres:/var/lib/postgresql/data
    ports:
    - "5662:5432"
    networks:
    - irene_network_prod

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
    - "9090:80"
    networks:
    - irene_network_prod
    depends_on:
    - db
    
networks:
  irene_network_prod:
    driver: bridge
